name: lint

on:
  pull_request:

jobs:
  lint:
    container: mumoshu/conflint:latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: conflint
      run: |
        pwd
        ls -lah
        apt-get update -y
        apt-get install git -y
        conflint run -efm "%f:%l:%c: %m" | reviewdog -efm="%f:%l:%c: %m" -reporter=github-pr-check
